<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [1]:
import numpy as np

## Exercise 1

| **Term**   | **Brief description**                                        |
|------------|--------------------------------------------------------------|
| Subsetting | Subsetting refers to selecting                               |
| Indexing   | Selecting single elements                                    |
| Slicing    | Selecting multiple elements                                  |
| Masking    | Removing one entire segment of an array to keep what remains |

## Exercise 2

In [15]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_1d = np_array_2d[:, 0]
array_int = np_array_1d.astype(int)
array_int %= 2
array_odd_int = (array_int == True)
array_odd_alp = np_array_2d[array_odd_int]
print(array_odd_alp[:, 1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [26]:
array_main = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
array_below = array_main < 50
array_below = array_below.astype(int)*(-1)
array_above = array_main > 50
array_above = array_above.astype(int)
array_final = array_above + array_below

print(array_final)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
